apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-kong-admin-pv-nfs
  labels:
    type: mongo-pv-nfs
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <nfs-server-ip>
    path: "/root/NFS_DATA/K8DATA"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-kong-admin-pvc-nfs
  namespace: kong
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi 

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: postgres-kong-admin-pvc-nfs 
      containers:      
      - env:
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          value: kong
        - name: POSTGRES_DB
          value: kong
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:9.5
        name: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: datadir
          subPath: pgdata
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kong
spec:
  selector:
    app: postgres
  ports:
    - name: psql
      port: 5432        
      protocol: TCP  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga    
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        env:
        - name: NODE_ENV
          value: development
        - name: DB_ADAPTER
          value: postgres
        - name: DB_URI
          value: postgresql://kong:kong@postgres:5432/konga_db
        - name: TOKEN_SECRET
          value: iu7YDcPLiZkozQXzZ9kka3Ee1Vid5ZgQ
        ports:
        - containerPort: 1337
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: konga-svc
  namespace: kong
spec:
  type: NodePort
  selector:
    app: konga
  ports:
    - name: konga-port
      port: 1337       
      nodePort: 31337 



