apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: jwt-user
  annotations:
    kubernetes.io/ingress.class: kong
username: jwt-user
custom_id: jwt-user
credentials:
- assad-jwt
- api-user-acl