kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30800 # kong proxy
    hostPort: 8000
  - containerPort: 30801 # kong admin api
    hostPort: 8001
  - containerPort: 31337 # konga 
    hostPort: 1337
  - containerPort: 31336 #Elastic search
    hostPort: 1336

